### ISSUE TITLE
Unexpected error invalid character '<'

### ISSUE THREAD

**Issue by sklinkert** [ravernkoh/deepl#2]
Looks like the lib broken. Even the tests are failing:

`
$ go test`
`--- FAIL: TestSplitIntoSentences [(0.20s)]`
`        client_test.go:34: Test 1: Unexpected error invalid character '<' looking for beginning of value.`
`--- FAIL: TestTranslate (0.03s)`
 `       client_test.go:73: Test 1: Unexpected error invalid character '<' looking for beginning of value.`
`FAIL`
`exit status 1`
`FAIL    github.com/ravernkoh/deepl      0.234s`

**Comment by tegk** [comment]
As he is not responding to the issues I forked to fix it.
https://github.com/tegk/deepl

**Comment by ravern** [comment]
Sorry for the late response, I have not been actively watching this repo 😓I don't think I will be working on this repo anytime soon, but if @tegk submits a PR I would gladly merge it. Alternatively, you can just use @tegk's fork.

Again, apologies for the lack of response.
